name: Advanced R
markdown: redcarpet
highlighter: pygments

exclude: ["README.md", "rep-res-course.Rproj", "temp.Rmd", "temp.html", "build-site.sh", "extras"]
baseurl: http://eriqande.github.io/test-pages
permalink: /blog/:month-:day-:year-:title.html


